---
- name: "Eza: Gathering packages facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Eza: Adding GPG Key"
  when: "'eza' not in ansible_facts.packages"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /etc/apt/keyrings/gierens.asc
    mode: "644"
    force: true
  become: true

- name: "Eza: Adding repository"
  when: "'eza' not in ansible_facts.packages"
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ ansible_facts.packages.bash[0].arch }} signed-by=/etc/apt/keyrings/gierens.asc]
      http://deb.gierens.de stable main
    filename: gierens
    state: present
    update_cache: true
  become: true
  register: apt_status
  until: apt_status is not failed
  retries: 5
  delay: 5

- name: "Eza: Installing"
  when: "'eza' not in ansible_facts.packages"
  ansible.builtin.apt:
    name: eza
    state: present
  become: true
  register: apt_status
  until: apt_status is not failed
  retries: 5
  delay: 5
