---
- name: Machine setup
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
    - name: Packages
      tags: basic
      block:
        - name: "Packages: Installing basic stuff"
          ansible.builtin.apt:
            name:
              - bfs
              - zsh
              - yakuake
              - tmux
              - okular-extra-backends
            update_cache: true
            state: present
          become: true

        - name: Change shell to zsh
          ansible.builtin.user:
            name: "{{ the_user }}"
            shell: /usr/bin/zsh
          become: true

    - name: Web Browsers
      tags: web
      block:
        - name: Firefox
          ansible.builtin.import_tasks: tasks/utils/firefox.ansible.yml

        - name: Chrome
          ansible.builtin.import_tasks: tasks/utils/chrome.ansible.yml

    - name: Development
      tags: dev
      block:
        - name: Delta
          ansible.builtin.import_tasks: tasks/dev/delta.ansible.yml

        - name: Neovim
          ansible.builtin.import_tasks: tasks/dev/neovim.ansible.yml

        - name: Jetbrains Toolbox
          ansible.builtin.import_tasks: tasks/dev/jetbrains_toolbox.ansible.yml

        - name: Code
          ansible.builtin.import_tasks: tasks/dev/code.ansible.yml

        - name: GitHub CLI
          ansible.builtin.import_tasks: tasks/dev/github_cli.ansible.yml

        - name: Docker
          ansible.builtin.import_tasks: tasks/dev/docker.ansible.yml

    - name: Fonts
      tags: fonts
      block:
        - name: "Fonts: Creating target directory"
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.local/share/fonts"
            state: directory
            mode: "775"
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"

        - name: Jetbrains Mono Font
          ansible.builtin.import_tasks: tasks/fonts/jetbrains_mono.ansible.yml

        - name: Jetbrains Mono Nerd Font
          ansible.builtin.import_tasks: tasks/fonts/jetbrains_mono_nerd.ansible.yml

        - name: MesloLGS NF Font
          ansible.builtin.import_tasks: tasks/fonts/meslolgs_nf.ansible.yml

    - name: Utilities
      tags: utils
      block:
        - name: Bat
          ansible.builtin.import_tasks: tasks/utils/bat.ansible.yml

        - name: Eza
          ansible.builtin.import_tasks: tasks/utils/eza.ansible.yml

        - name: Zoxide
          ansible.builtin.import_tasks: tasks/utils/zoxide.ansible.yml

        - name: Fzf
          ansible.builtin.import_tasks: tasks/utils/fzf.ansible.yml
