---
- name: Machine setup
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Packages
      tags: basic
      block:
        - name: "Packages: Installing basic stuff"
          ansible.builtin.apt:
            name:
              - zsh
              - yakuake
              - okular-extra-backends
              - mpv
            update_cache: true
            state: present
          become: true

        - name: "Packages: Uninstalling default neovim"
          ansible.builtin.apt:
            name: neovim
            state: absent
          become: true

        - name: "Packages: Change login shell to zsh"
          ansible.builtin.shell:
            cmd: chsh -s $(which zsh)
          register: zsh
          changed_when: zsh.rc != 0
          become: true

    - name: Web Browsers
      tags: web
      block:
        - name: Firefox
          ansible.builtin.import_tasks: tasks/utils/firefox.ansible.yml

        - name: Chrome
          ansible.builtin.import_tasks: tasks/utils/chrome.ansible.yml

    - name: Development
      tags: dev
      block:
        - name: Delta
          ansible.builtin.import_tasks: tasks/dev/delta.ansible.yml

        - name: Neovim
          ansible.builtin.import_tasks: tasks/dev/neovim.ansible.yml

        - name: Jetbrains Toolbox
          ansible.builtin.import_tasks: tasks/dev/jetbrains_toolbox.ansible.yml

        - name: Code
          ansible.builtin.import_tasks: tasks/dev/code.ansible.yml

        - name: GitHub CLI
          ansible.builtin.import_tasks: tasks/dev/github_cli.ansible.yml

        - name: Docker
          ansible.builtin.import_tasks: tasks/dev/docker.ansible.yml

    - name: Fonts
      tags: fonts
      block:
        - name: "Fonts: Creating target directory"
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.local/share/fonts"
            state: directory
            mode: "775"
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"

        - name: Jetbrains Mono Font
          ansible.builtin.import_tasks: tasks/fonts/jetbrains_mono.ansible.yml

        - name: Jetbrains Mono Nerd Font
          ansible.builtin.import_tasks: tasks/fonts/jetbrains_mono_nerd.ansible.yml
