---
- name: "Docker: Gathering packages facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Docker: Removing old packages"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true
  register: apt_status
  until: apt_status is not failed
  retries: 5
  delay: 5

- name: "Docker: Adding GPG Key"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "644"
    force: true
  become: true

- name: "Docker: Adding repository"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ ansible_facts.packages.bash[0].arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: true
  become: true
  register: apt_status
  until: apt_status is not failed
  retries: 5
  delay: 5

- name: "Docker: Installing"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  register: apt_status
  until: apt_status is not failed
  retries: 5
  delay: 5

- name: "Docker: Checking group existence"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Docker: Adding user to docker group"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups: docker
  become: true

- name: "Docker: Start on boot 1"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
  become: true

- name: "Docker: Start on boot 2"
  when: "'docker-ce' not in ansible_facts.packages"
  ansible.builtin.systemd_service:
    name: containerd
    enabled: true
  become: true
