---
- name: "Jetbrains Nerd Font: Checking if font is installed"
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.local/share/fonts"
    patterns: 'JetBrainsMonoNerdFontMono-*'
  register: jetbrains_nerd_fonts

- name: "Jetbrains Nerd Font: Getting effective url"
  when: jetbrains_nerd_fonts.matched == 0
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
  register: result

- name: "Jetbrains Nerd Font: Downloading"
  when: jetbrains_nerd_fonts.matched == 0
  ansible.builtin.get_url:
    url: "{{ result.json.assets[78].browser_download_url }}"
    dest: /tmp
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: "Jetbrains Nerd Font: Unzipping zip"
  when: jetbrains_nerd_fonts.matched == 0
  ansible.builtin.unarchive:
    src: "/tmp/{{ result.json.assets[78].browser_download_url | basename }}"
    dest: "/tmp"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: "Jetbrains Nerd Font: Copying files"
  when: jetbrains_nerd_fonts.matched == 0
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_fileglob:
    - "/tmp/JetBrainsMonoNerdFontMono-*"

- name: "Jetbrains Nerd Font: Updating cache fonts"
  when: jetbrains_nerd_fonts.matched == 0
  ansible.builtin.shell:
    cmd: fc-cache -f -v
    executable: /bin/bash
  register: font_cache
  changed_when: font_cache.rc != 0
